# Generated by Django 4.2.13 on 2024-06-20 22:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AssetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.BigIntegerField()),
                ('uniqueID', models.CharField(max_length=255, unique=True)),
                ('assetValue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.assetvalue')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetID', models.CharField(max_length=50, null=True, unique=True)),
                ('detailID', models.IntegerField()),
                ('creatorID', models.BigIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'In Sale'), (2, 'Processing'), (3, 'Sold')], default=1)),
                ('descriptions', models.JSONField()),
                ('deliveryMethod', models.IntegerField(choices=[(1, 'Trade'), (2, 'Gift')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tradeableAt', models.DateField(default=datetime.date.today)),
                ('creatorShare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.assetvalue')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiatorID', models.BigIntegerField()),
                ('initiatorRecieved', models.BooleanField(default=False)),
                ('sellerSent', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Done'), (4, 'Canceled')], default=1)),
                ('finalTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalizedOrder', to='market.transaction', unique=True)),
                ('initialTransaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiatedOrder', to='market.transaction', unique=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.product')),
            ],
        ),
    ]
