# Generated by Django 4.2.13 on 2024-06-21 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_order_finaltransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tradeableAt',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
