# Generated by Django 4.2.13 on 2024-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(choices=[('BTC', 'BTC'), ('USDT', 'USDT'), ('TOMAN', 'TOMAN')], max_length=5, unique=True),
        ),
    ]
