# Generated by Django 4.2.13 on 2024-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sellerDeliverAt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='initiatorRecieved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sellerSent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
