# Generated by Django 4.2.13 on 2024-06-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_asset_decimal_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(choices=[('SATOSHI', 'SATOSHI'), ('USDT', 'USDT'), ('TOMAN', 'TOMAN')], max_length=7, unique=True),
        ),
    ]
