# Generated by Django 4.2.13 on 2024-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.JSONField(null=True),
        ),
    ]
