# Generated by Django 4.2.13 on 2024-06-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_product_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isUnique',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'In Sale'), (3, 'Processing'), (4, 'Sold')], default=2),
        ),
    ]
