# Generated by Django 4.2.13 on 2024-06-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='TOTPKey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vipExpiration',
        ),
        migrations.AddField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='VIPBTCAddress',
        ),
    ]
