# Generated by Django 4.2.13 on 2024-06-19 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_totpkey_remove_user_vipexpiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobileNumber',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='canSell',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id64',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kycLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='steamAPIKey',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tradeURL',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('rejectionReasson', models.CharField(blank=True, max_length=50, null=True)),
                ('fileName', models.CharField(max_length=30)),
                ('isAccepted', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='KYCs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=20, unique=True)),
                ('isAccepted', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BankCards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
