# Generated by Django 4.2.13 on 2024-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_mobilenumber_user_mobile_user_cansell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='canSell',
            field=models.BooleanField(default=False),
        ),
    ]
