# Generated by Django 4.2.13 on 2024-06-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('appid', models.IntegerField(choices=[(570, 'DOTA2'), (730, 'CS2'), (440, 'TF2')])),
                ('importantNumber', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imageName', models.CharField(max_length=50)),
                ('imageURL', models.TextField()),
                ('imageBigURL', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('appid', models.IntegerField(choices=[(570, 'DOTA2'), (730, 'CS2'), (440, 'TF2')], default=570)),
                ('uploaded', models.BooleanField(default=False)),
                ('importantLevel', models.IntegerField(default=1)),
                ('tags', models.ManyToManyField(blank=True, to='market.tag')),
            ],
        ),
    ]
