# Generated by Django 4.2.13 on 2024-06-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_detail_imagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='descriptions',
        ),
    ]
