# Generated by Django 4.2.13 on 2024-06-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_detail_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='imageBigURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Details', to='market.tag'),
        ),
    ]
